### PR TITLE
[YUNIKORN-283] Support query params to filter the apps using queue name/namespace for v1/apps endpoint 

### PR DESCRIPTION
**Pull request by manirajv06**

### CODE REVIEW

**Comment by manirajv06** [comment]
@wilfred-s can you please take a look at doc changes as well?

**Comment by wilfred-s** [comment]
We used to have a nice message on the top of the repo to point everyone to the instructions on the [master branch](https://github.com/apache/incubator-yunikorn-site/tree/master)

Doc changes are made in master as simple md file changes. We can review them there. Please open the doc change as a new PR against the master branch. I don't think it is going to be easy to modify this PR to do that.

**Comment by yangwwei** [comment]
hi @manirajv06 

Thanks for working on this. Like @wilfred-s  mentioned, please open a PR against the master branch. All the site update happens automatically once the PR is merged into the master branch.

For this doc, I think you need to update the MD file directly in https://github.com/apache/incubator-yunikorn-site/tree/master/docs/api. And you can run a local build to verify the changes.

Thanks

**Comment by manirajv06** [comment]
@wilfred-s @yangwwei Thanks for details. Created a PR https://github.com/apache/incubator-yunikorn-site/pull/14. Please take a look. Closing this.

**Pull request closed without merging**
