### PR TITLE
[YUNIKORN-726] Add instructions to approve cert requests

### PR DESCRIPTION
**Pull request by holdenk**
These requests may not be auto-approved in newer version of Kubernetes

### CODE REVIEW

**Comment by wilfred-s** [comment]
This is the line that approves the request in the [script](https://github.com/apache/incubator-yunikorn-k8shim/blob/0bd93660ec8b9b99dd28ae93ea755a52d0187741/deployments/admission-controllers/scheduler/generate-signed-ca.sh#L91)
Is this related to YUNIKORN-625 and indirectly YUNIKORN-674? If so we should work on that issue. I have mentioned in discussion before that we should use go code and not a shell script to deploy the admin controller. That would allow us to recompile the admin deployment code for specific K8s versions.

**Comment by wilfred-s** [comment]
Based on the changes we have made there is no longer a script and we no longer need to approve any certificates.
@holdenk I think this has been made obsolete with the new deployment code of the admission controller. 
I think we can close this one, please confirm if that is correct.

**Comment by craigcondit** [comment]
> Based on the changes we have made there is no longer a script and we no longer need to approve any certificates.

Correct.  

> @holdenk I think this has been made obsolete with the new deployment code of the admission controller.

Correct. 

> I think we can close this one, please confirm if that is correct.

Yes we can close this one.

**Comment by craigcondit** [comment]
Closing, as this is no longer needed.

**Pull request closed without merging**
