### PR TITLE
[YUNIKORN-1064] Doc changes for YUNIKORN-958 & YUNIKORN-960

### PR DESCRIPTION
**Pull request by anuraagnalluri**

### CODE REVIEW

**Comment by anuraagnalluri** [comment]
FYI @manirajv06

**Comment by manirajv06** [comment]
doc changes looks good. In addition, can see some stack trace changes as well. Are these changes intentional?

**Comment by anuraagnalluri** [comment]
@manirajv06 The stack trace changes weren't intentional. It just auto-formatted upon pushing the commit. If I copy the `Content examples` block from [here](https://github.com/apache/incubator-yunikorn-site/blob/master/docs/api/scheduler.md#goroutines-info) and paste it in my editor, I can't see any changes in `git status`. But it seems to automatically delete a tab from most of these indents on the github diff view.

**Comment by manirajv06** [comment]
Something is different here as I can see a clean code diff in another doc related PR you done recently. Can you please check this in detail and fix?

**Comment by anuraagnalluri** [comment]
@manirajv06 Fixed.

**Review by manirajv06 — APPROVED** [review]
Thank you. Committing..

**Pull request merged**
